### ISSUE TITLE
Learn React, Vue, Svelte or Angular stop this.

### ISSUE THREAD

**Issue by litesam** [sprince0031/Ember-Learning#1]
For a good start on web development learn Svelte first their model is so great that you will start to embrace that instead of other models.

I can even give you the benefits for why using the alternatives instead of Ember will make your life easier.

**Comment by litesam** [comment]
He explained on why he is using Ember.

**Comment by sprince0031** [comment]
Thank you for your suggestion Sam! Svelte seems to be quite interesting. Will definitely take a look into that and try a couple of side projects.
